# Generated by Django 3.2.21 on 2023-09-21 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='expert_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.BigIntegerField()),
                ('ph_no', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='suggestion_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_range', models.CharField(max_length=20)),
                ('suggestion', models.CharField(max_length=20)),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.expert_table')),
            ],
        ),
        migrations.CreateModel(
            name='study_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=20)),
                ('study_material', models.CharField(max_length=20)),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.expert_table')),
            ],
        ),
        migrations.CreateModel(
            name='staff_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.BigIntegerField()),
                ('ph_no', models.BigIntegerField()),
                ('Class', models.CharField(max_length=20)),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='parent_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('ph_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=20)),
                ('Class', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=20)),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.parent_table')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.staff_table')),
            ],
        ),
        migrations.AddField(
            model_name='expert_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.login_table'),
        ),
        migrations.CreateModel(
            name='doubt_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doubt', models.CharField(max_length=20)),
                ('reply', models.CharField(max_length=20)),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.expert_table')),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.parent_table')),
            ],
        ),
        migrations.CreateModel(
            name='daily_activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=20)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.staff_table')),
            ],
        ),
        migrations.CreateModel(
            name='chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.parent_table')),
            ],
        ),
        migrations.CreateModel(
            name='chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=20)),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to='studentapp.login_table')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_id', to='studentapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='attendence_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendence', models.CharField(max_length=20)),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.parent_table')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.staff_table')),
            ],
        ),
    ]
