# Generated by Django 3.2.21 on 2023-09-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence_table',
            name='attendence',
            field=models.BigIntegerField(),
        ),
    ]
