# Generated by Django 3.2.21 on 2023-09-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_attendence_table_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_material',
            name='Class',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='study_material',
            name='study_material',
            field=models.FileField(upload_to=''),
        ),
    ]
