# Generated by Django 3.2.21 on 2023-11-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_rename_student_name_parent_table_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert_table',
            name='email',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff_table',
            name='email',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
