# Generated by Django 3.2.21 on 2023-11-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_auto_20231103_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert_table',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parent_table',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff_table',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
