# Generated by Django 3.2.21 on 2023-11-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_auto_20231103_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='PARENT',
        ),
        migrations.DeleteModel(
            name='dataset',
        ),
        migrations.AlterField(
            model_name='daily_activities',
            name='activity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_activities',
            name='details',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doubt_table',
            name='doubt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doubt_table',
            name='reply',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suggestion_table',
            name='mark_range',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suggestion_table',
            name='suggestion',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='chatbot',
        ),
    ]
