# Generated by Django 3.2.21 on 2023-11-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0009_chatbot_dataset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion_table',
            old_name='mark_range',
            new_name='mark',
        ),
        migrations.AlterField(
            model_name='chat_table',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
