# Generated by Django 3.2.21 on 2023-11-11 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0010_auto_20231111_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='question',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='DATASET',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentapp.dataset'),
            preserve_default=False,
        ),
    ]
