# Generated by Django 3.2.21 on 2023-11-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0012_suggestion_table_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion_table',
            name='mark',
            field=models.IntegerField(),
        ),
    ]
